package com.example.ai;

public enum XPlaneEventType {
    SESSION_START,
    SESSION_STOP,
    RECEIVER_START,
    RECEIVER_STOP,
    RECEIVER_ERROR,
    MANUAL_NOTE,
    TRIAL_RESET,
    TRIAL_START,
    TRIAL_END,
    SCENARIO_MARKER,
    FINAL_APPROACH_GATE_ENTERED,
    SCENARIO_SELECTED,
    INTRUDER_SPAWNED,
    ADVISORY_SHOWN,
    ADVISORY_CLEARED,
    HAZARD_DETECTED,
    HAZARD_CLEARED,
    MIN_DISTANCE_REACHED,
    GO_AROUND_START,
    GO_AROUND_CONFIRMED,
    PILOT_RESPONSE_START,
    PILOT_RESPONSE_END
}
